id: P004146
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16726
  title: རྭ་སྟོད་བསྡུས་གྲྭ།
  author: ''
  volumes:
    7f9c9283c2aa4508ba26ff000b3f9651:
      image_group_id: I1KG18288
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
    d93ec16d4964410fb512e6f549d63d55:
      image_group_id: I1KG18289
      title: ''
      volume_number: 2
      total_pages: 302
      base_file: v002.txt
