id: IA8131F8F
legacy_id: P004146
ocr_import_info:
  bdrc_scan_id: W1KG16726
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T05:40:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:14:44.195977+00:00'
last_modified: 2022-08-27 14:15:42.187593
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16726
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16726
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྭ་སྟོད་བསྡུས་གྲྭ།
  author: ཤངས་པ་ཀུན་མཁྱེན་མཆོག་ལྷ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.8349545396109375
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG18289:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18289
      total_pages: 302
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG18289.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8305990255962302
    legacy_id: v002
  I1KG18288:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18288
      total_pages: 276
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18288.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.839895480032556
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
